### ISSUE TITLE
Support other .NET versions.

### ISSUE THREAD

**Issue by gustavo-frizzo** [gustavofrizzo/CreditCardValidator#1]
.NET 3.5 +

**Comment by PureKrome** [comment]
This can be closed because of #2 ... unless .... you want a `.NET 3.5` nuget _package_ up on nuget.org ... which I didn't do. I just did the prj code .. so a person will have to _manually_ compile the code and use the `.dll` manually.

**Comment by gustavo-frizzo** [comment]
Yes! Closing...

I created the package using a tool (NuGet Package Explorer). So, I included the dll for .NET 3.5 in it too.

**Comment by PureKrome** [comment]
Nice work! If there's any probs i'll post another issue (or PR :)  )
