### ISSUE TITLE
Lets move this to .netstandard

### ISSUE THREAD

**Issue by jzeferino** [gustavofrizzo/CreditCardValidator#11]
Can I help with that?

**Comment by gustavo-frizzo** [comment]
To support .netstandard, I believe the only change would be on the "TargetFrameworks" element in the project file and then update the nuget package.
Basically there is no coding :p

Do you need support for .netstandard?

**Comment by andrei-m-code** [comment]
netstandard2.0 would be great!

**Comment by jzeferino** [comment]
Yes I need. But we should remove PCL support and maybe 35 framrwork.

**Comment by gustavo-frizzo** [comment]
Alright. I will add support to .netstandard this weekend.

There is no need to remove PCL and .net3.5. After all, people still use them.

**Comment by gustavo-frizzo** [comment]
The new package (1.4.6) was uploaded:
https://www.nuget.org/packages/CreditCardValidator/1.4.6

Thanks for the suggestion :)
