### ISSUE TITLE
CreditCardDetector empty constructor

### ISSUE THREAD

**Issue by rclark381** [gustavofrizzo/CreditCardValidator#12]
I would like to use the `CreditCardDetector` more or less as a singleton in my app, but the constructor requiring a card number means I have to new up an instance every time to check a card. Has moving the card number to be a parameter on the `IsValid` function been explored?

**Comment by gustavo-frizzo** [comment]
Hey
Having one instance of CreditCardDetector being accessed in a multithread environment would cause concurrency issues (in case that IsValid could receive a card number as parameter). Unless you would control the access in your singleton. 

But I believe would be possible to provide a static method (or something like that) that receives a string and returns a CardIssuer or check if the card IsValid without instantiating new objects every time.

Do you think that would work for you?

**Comment by rclark381** [comment]
@gustavofrizzo after further investigation, I believe a CreditCardDetectorFactory in my own code will accomplish what I am needing. I also realize that I am not wanting a singleton, but an instance per request - for dependency injection. The factory on my end will get me there.

Thank you for the follow up and offer to create static methods.
