### ISSUE TITLE
CreditCardFactory sometimes generates number matching some brand for parameter CardIssuer.Unknown

### ISSUE THREAD

**Issue by dobreffandras** [gustavofrizzo/CreditCardValidator#15]
# Current behavior
```csharp
var input = CreditCardFactory.RandomCardNumber(CardIssuer.Unknown);
```
Sometimes generates numbers that will match for known Card issuers. 

E.g.: `"344447596032225"` matches `CardIssuer.AmericanExpress`. 
```csharp
var brand = new CreditCardDetector("344447596032225").Brand;
```

# Expected behavior
`CreditCardFactory.RandomCardNumber` generates numbers with prefixes that match none of the known card issuers for `CardIssuer.Unknown`.

**Comment by gustavo-frizzo** [comment]
Fixed on version 2.0.0 of the package. 

Thanks!
