### ISSUE TITLE
NullReferenceException : Object reference not set to an instance of an object. in nunit parallel mode

### ISSUE THREAD

**Issue by EvgenyMarchuk** [gustavofrizzo/CreditCardValidator#18]
There is a simple example to reproduce the problem.
Create several(3 or more) tests for Nunit project
You should generate a new card number for each test

`[Parallelizable(ParallelScope.All)]
    internal class SimpleTests
    {
        [Test]
        public void SimpleTest1()
        {
            var cardNumber = CreditCardFactory.RandomCardNumber(CardIssuer.MasterCard);
            Assert.IsNotNull(cardNumber);
        }

        [Test]
        public void SimpleTest2()
        {
            var cardNumber = CreditCardFactory.RandomCardNumber(CardIssuer.MasterCard);
            Assert.IsNotNull(cardNumber);
        }

        [Test]
        public void SimpleTest3()
        {
            var cardNumber = CreditCardFactory.RandomCardNumber(CardIssuer.MasterCard);
            Assert.IsNotNull(cardNumber);
        }

        [Test]
        public void SimpleTest4()
        {
            var cardNumber = CreditCardFactory.RandomCardNumber(CardIssuer.MasterCard);
            Assert.IsNotNull(cardNumber);
        }
    }`

![image](https://user-images.githubusercontent.com/10145980/85841447-d0937400-b7a6-11ea-8cf7-87024488b77b.png)

**Comment by gustavo-frizzo** [comment]
Published version 2.0.1 with the fix.
Thanks for reporting it.
