### ISSUE TITLE
PCL 259 Support

### ISSUE THREAD

**Issue by cbrammer** [gustavofrizzo/CreditCardValidator#4]
First off, thanks for creating this and sharing it. Second, what are the chances you could add support for PCL 259 (Xamarin PCL)? I think your code supports it already, just not published for it.

**Comment by gustavo-frizzo** [comment]
Hi, 

Thanks for the suggestion. 

I was taking a look and seems that we just have to add the "Windows Phone Silverlight 8.0" target to support PCL 259, right?

I will check if it works and then I will update the package.

Best regards,
Gustavo Frizzo.

**Comment by homerokzam** [comment]
Any news?

Thanks,
Homero

**Comment by gustavo-frizzo** [comment]
Added PCL 259 support. 147ea8ff12b28c969e7d0457e660cd07c3ef45fb
Nuget Version 1.4.5

Thanks!
