### ISSUE TITLE
Feature Request: Support for newer payment account number formats

### ISSUE THREAD

**Issue by bsweeney** [gustavofrizzo/CreditCardValidator#6]
Visa and MasterCard now support issuance of 19-digit account numbers. Would like to see the validation updated to support these new formats.

Reference: https://en.wikipedia.org/wiki/Payment_card_number

**Comment by gustavo-frizzo** [comment]
Added support for Visa 19 digits cards.
7120448d00c1f9e4e702282f7a81ae49c9e5a2f8
Nuget package version 1.4.5
