### ISSUE TITLE
.NetCore

### ISSUE THREAD

**Issue by jsears** [gustavofrizzo/CreditCardValidator#7]
Will you ever update this to be compatible with .NetCore?  I'm currently getting the following when attempting to add this to my project with the following error message:
Install-Package : Package CreditCardValidator 1.4.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package CreditCardValidator 1.4.0 supports:

**Comment by semack** [comment]
Added PR #8

**Comment by gustavo-frizzo** [comment]
@jsears , were you able to install the version 1.4.1?

**Comment by jsears** [comment]
I created a new project and targeted .netcore myself.
