### ISSUE TITLE
Signed Version in NuGet

### ISSUE THREAD

**Issue by MarkLFT** [gustavofrizzo/CreditCardValidator#9]
This is a very useful library. But I think it would be more useful if the library is signed, as currently I cannot use NuGet to get this library.

**Comment by gustavo-frizzo** [comment]
Hey!
Are you talking about strong names, right?

I was reading about it:
- https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/
- https://github.com/octokit/octokit.net/issues/405
- https://twitter.com/eric_sink/status/623939641687830529
- https://github.com/libgit2/libgit2sharp/issues/212

Looks like it may not be worth signing the assemblies. But if you really need you can fork the project and create your own signed assembly. It looks pretty straightforward.

**Comment by MarkLFT** [comment]
Many thanks for your reply, and I agree strong names can be a pain.  Unfortunately they are still a necessity.  We have a very large solution, that contains around one hundred projects, all inter-dependent, and the problem we have is several of our core programs force us to use signing, this in turn means we can only use signed libraries.

We are well aware of branching, and self-signing, but this comes with even bigger perils.  Until recently we used a library in such a way.  The problem is, sometimes the developers forget this library has a self-signed version, and pull an upgraded version from nuget.  As the compiler does not pick up problem, it is not until runtime we find out.  This has caused us headaches a few times, so we have basically had to stop using any libraries that require self-signing.

As the top story to mention stated, it takes 2 seconds to sign a library, and once signed, can be used by anyone, you cannot say the same about the unsigned version.  The issue of versioning, again, just rely on the nuget versioning, and all works fine.

I understand if you don’t want to sign it, I have had the same discussion with a few other developers, it just means I, and many other developers will be easily be able to use your library.

Best regards

Mark

**Comment by gustavo-frizzo** [comment]
Hey, 
I see. I will take a better look at that.
So, the best solution would be to freeze the dll version (2.0.0 would work, right?) and then update only the nuget version?

If so, this process seems to be fairly simple and I guess it won't affect projects that already use it.
